apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-default-conf
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;


        location / {
            proxy_pass http://drupal-svc:9999;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
