apiVersion: v1
kind: Service
metadata:
  name: {{ "Values.drupal.service.name"  }}
  labels:
    app: drupal
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.drupal.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: drupal
