apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.service.name }}
  labels:
    app: nginx
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: nginx
