apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drupal
spec:
  ingressClassName: traefik
  rules:
  -   host: "{{ .Values.drupal.ingress.hostName }}"
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.drupal.service.name }}
              port:
                number: {{ .Values.drupal.service.port }}
