apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.wordpress.service.name  }}
  labels:
    app: wordpress
spec:
  type: {{ .Values.wordpress.service.type }}
  ports:
    - port: {{ .Values.wordpress.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: wordpress
