apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web
  name: web
  namespace: hello-nginx
spec:
  containers:
  - image: nginx:latest
    name: web
  dnsPolicy: ClusterFirst
  restartPolicy: Always
